[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Disable the watchdog that monitors file changes
fileWatcherType = "none"

# If you want to selectively disable only for certain modules, you can use:
# enableXsrfProtection = false
# enableStaticServing = true

maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[runner]
# Sets the number of seconds to wait for the script to stop when rerunning
fastReruns = true

magicEnabled = true

[main]
# Set the main file to streamlit_app.py
mainFile = "streamlit_app.py"
